export const cardImages = {
  'ablaze-alchemist': require('../assets/cards/fire/AblazeAlchemist.png'),
  'ashen-assassin': require('../assets/cards/fire/AshenAssassin.png'),
  'blazing-archer': require('../assets/cards/fire/BlazingArcher.png'),
  'blazing-shiv': require('../assets/cards/fire/BlazingShiv.png'),
  'bonfire-behemoth': require('../assets/cards/fire/BonfireBehemoth.png'),
  'burning-blade-initiate': require('../assets/cards/fire/BurningBladeInitiate.png'),
  'charred-chieftain': require('../assets/cards/fire/CharredChieftain.png'),
  'cinder-beast': require('../assets/cards/fire/CinderBeast.png'),
  'coal-colossus': require('../assets/cards/fire/CoalColossus.png'),
  'ember-enchanter': require('../assets/cards/fire/EmberEnchanter.png'),
  'ember-scout': require('../assets/cards/fire/EmberScout.png'),
  'ember-spirit': require('../assets/cards/fire/EmberSpirit.png'),
  'fire-acolyte': require('../assets/cards/fire/FireAcolyte.png'),
  'fire-elemental': require('../assets/cards/fire/FireElemental.png'),
  'firebrand-fiend': require('../assets/cards/fire/FirebrandFiend.png'),
  'flame-sprite': require('../assets/cards/fire/FlameSprite.png'),
  'flame-warrior': require('../assets/cards/fire/FlameWarrior.png'),
  'flame-witch': require('../assets/cards/fire/FlameWitch.png'),
  'flare-knight': require('../assets/cards/fire/FlareKnight.png'),
  'heat-haze-harpy': require('../assets/cards/fire/HeatHazeHarpy.png'),
  'hellfire-hydra': require('../assets/cards/fire/HellfireHydra.png'),
  'infernal-imp': require('../assets/cards/fire/InfernalImp.png'),
  'infernal-overlord': require('../assets/cards/fire/InfernalOverlord.png'),
  'inferno-hound': require('../assets/cards/fire/InfernoHound.png'),
  'inferno-incarnate': require('../assets/cards/fire/InfernoIncarnate.png'),
  'inferno-knight': require('../assets/cards/fire/InfernoKnight.png'),
  'lava-lurker': require('../assets/cards/fire/LavaLurker.png'),
  'lava-pool': require('../assets/cards/fire/LavaPool.png'),
  'magma-javelineer': require('../assets/cards/fire/MagmaJavelineer.png'),
  'magma-mauler': require('../assets/cards/fire/MagmaMauler.png'),
  'molten-giant': require('../assets/cards/fire/MoltenGiant.png'),
  'pyro-mage': require('../assets/cards/fire/PyroMage.png'),
  'pyrokinetic-charge': require('../assets/cards/fire/PyrokineticCharge.png'),
  'pyre-priest': require('../assets/cards/fire/PyrePriest.png'),
  'scorching-paladin': require('../assets/cards/fire/ScorchingPaladin.png'),
  'scorching-squire': require('../assets/cards/fire/ScorchingSquire.png'),
  'searing-swordsman': require('../assets/cards/fire/SearingSwordsman.png'),
  'sizzle-sprite': require('../assets/cards/fire/SizzleSprite.png'),
  'smolder-soldier': require('../assets/cards/fire/SmolderSoldier.png'),
  'spark-imp': require('../assets/cards/fire/SparkImp.png'),
  'spark-sorcerer': require('../assets/cards/fire/SparkSorcerer.png'),
  'sparksplit-shaman': require('../assets/cards/fire/SparksplitShaman.png'),
  'volcanic-drake': require('../assets/cards/fire/VolcanicDrake.png'),
  'wildfire-wyrm': require('../assets/cards/fire/WildfireWyrm.png'),
} as const;

// Add type safety for image keys
export type CardImageKey = keyof typeof cardImages; 